In [2]:
#*******************************************************************************************************#
#************************************* NUMPY ASSIGNMENT ************************************************#
#*******************************************************************************************************#

import numpy as np

In [19]:
# 3. Find the shape, size and dimension of the following array? [[1, 2, 3, 4] [5, 6, 7, 8], [9, 10, 11, 12]].

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

dimension = array.ndim

shape = array.shape

size = array.size

print(f"The dimension of an array is: {dimension}\nThe shape of an array is: {shape}\nThe size of an array is: {size} ")

The dimension of an array is: 2
The shape of an array is: (3, 4)
The size of an array is: 12 


In [24]:
# 4. Write python code to access the first row of the following array? [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]].

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

array[0]

array([1, 2, 3, 4])

In [27]:
# 5. How do you access the element at the third row and fourth column from the given numpy array? [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]].

#Ans:

array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

array[2][3]

12

In [48]:
# 6. Write code to extract all odd-indexes elements from the given numpy array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]].

#Ans:

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 1]])

odd_indices_array = array[1::2, 1::2]

odd_indices_array

array([[6, 8]])

In [52]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1 ?

#Code:

array = np.random.rand(3,3)

array

array([[0.04636612, 0.76548982, 0.89934975],
       [0.89706582, 0.44051917, 0.62511061],
       [0.91014212, 0.31236796, 0.43525046]])

In [69]:
# 9. Write code to increase the dimension of the following array? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]].

#Code:

original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reshaped_array = array.reshape(4,1,3)

reshaped_array.ndim

3

In [77]:
# 10. How to transpose the following array in NumPy? [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]].

#Code:

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

array.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [80]:
# 1. Index wise multiplication.

MatrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

MatrixA * MatrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [5]:
# 2.  Matrix multiplication.

MatrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

MatrixB = MatrixB.transpose()

np.dot(MatrixA, MatrixB)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [5]:
# 3. Add both the matrix.

MatrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

MatrixA + MatrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [8]:
# 4. Subtract matrix B from A.

MatrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

MatrixB - MatrixA

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
# 5. Divide Matrix B by A.

MatrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
MatrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

MatrixB / MatrixA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# 12. Which function in Numpy can be used to swap the byte order of an array?


array = np.array([1,23,3,4,5])

array.byteswap()

array([  72057594037927936, 1657324662872342528,  216172782113783808,
        288230376151711744,  360287970189639680])